staabm/phpstan-dba

src/QueryReflection/QueryReflection.php, tests/data/pdo.php
replacing a plain string with a candidate is pretty hard, as we atm don't know where wihtin the query the string is used.
we would need more information about the query structure to find a proper replace candidate.
=> remove plain-string interpolation for now

config/Mysqli.stub
=> php7.x compat for the mysqli stub

.phpstan-dba.cache, tests/data/mysqli.php, tests/data/pdo.php
these cases are supported with the newly added mysqli->real_escape_string() and pdo->quote() return type extensions
=> cover quoted query strings with tests

README.md, bootstrap.php, src/Extensions/MysqliEscapeStringDynamicReturnTypeExtension.php, src/Extensions/MysqliQueryDynamicReturnTypeExtension.php, src/Extensions/PdoPrepareDynamicReturnTypeExtension.php, src/Extensions/PdoQueryDynamicReturnTypeExtension.php, src/Extensions/PdoQuoteDynamicReturnTypeExtension.php, src/Extensions/PdoStatementColumnCountDynamicReturnTypeExtension.php, src/Extensions/PdoStatementFetchDynamicReturnTypeExtension.php, src/QueryReflection/QueryReflection.php, src/QueryReflection/RuntimeConfiguration.php, tests/data/mysqli-escape.php, tests/data/mysqli.php, tests/data/pdo-fetch-types.php, tests/data/pdo-quote.php, tests/data/pdo-stmt-fetch.php, tests/data/pdo.php
see also https://github.com/php/doc-en/pull/1313
- when analyzing a php8+ codebase, [`PDO::ERRMODE_EXCEPTION` error handling](https://www.php.net/manual/en/pdo.error-handling.php) is assumed.
- when analyzing a php8.1+ codebase, [`mysqli_report(\MYSQLI_REPORT_ERROR | \MYSQLI_REPORT_STRICT);` error handling](https://www.php.net/mysqli_report) is assumed.
=> remove `false` from return types, when error mode is exception

.phpstan-dba.cache, src/Extensions/PdoExecuteTypeSpecifyingExtension.php, tests/data/pdo-stmt-execute.php
see https://stackoverflow.com/questions/48643967/php-pdo-prepared-statement-bind-null-value
=> support null and string-values in prepared statements

.phpunit-phpstan-dba.cache, bootstrap.php
we need to record the reflection information in both, phpunit and phpstan since we are replaying it in both CI jobs.
in a regular application you will use phpstan-dba only within your phpstan CI job, therefore you only need 1 cache-file.
phpstan-dba itself is a special case, since we are testing phpstan-dba with phpstan-dba.
=> Fix `RecordingQueryReflector` to work phpstan and phpunit in tandem

.phpunit-phpstan-dba.cache, src/QueryReflection/MysqliQueryReflector.php
before this change the test-suite required 121 queries to the database.
after this change we need only 32 queries, because we no longer re-issue already executed queries
=> refactor `MysqliQueryReflector` to reduce numer of executed queries

src/QueryReflection/MysqliQueryReflector.php
While I'm here, for DATE/DATETIME I guess string is also the only reasonable output.. unless PHPStan has a concept of date-string (which would be kinda neat;)
=> Add support for JSON columns and nullability for string column types

src/Rules/PdoStatementExecuteMethodRule.php
Adding a simple `if (\count($namedPlaceholders) > 0) {` around the **named** placeholders checks.
This stops the following error when checking `$stmt->execute()` on a query using question mark parameters.
Value 0 is given to execute(), but the query does not contain this placeholder.
This is for [Issue 69](https://github.com/staabm/phpstan-dba/issues/69)
=> Do not run PDO namedPlaceholders checks with question mark parameters

.editorconfig, .phpstan-dba.cache, README.md, config/dba.neon, tests/SyntaxErrorInPreparedStatementMethodRuleTest.php, tests/config/syntax-error-in-prepared-statement.neon, tests/data/syntax-error-in-prepared-statement.php
This adds support for `executeQuery($sql, $params)`, `executeCacheQuery($sql, $params)`, `executeStatement($sql, $params)` 
`prepare($sql)` is not yet supported and can be implemented later
refs https://github.com/staabm/phpstan-dba/issues/94
=> Detect syntax errors in `Doctrine\DBAL\Connection::execute*()` methods

.phpstan-dba.cache, config/dba.neon
since we just need a few lines of config, we also cover the deprecated api.
> This API is deprecated and will be removed after 2022
=> doctrine dbal: cover deprecated api

.phpstan-dba.cache, .phpunit-phpstan-dba.cache, README.md, config/DoctrineDbal.stub, config/extensions.neon, config/stubFiles.neon, src/Extensions/DoctrineConnectionDynamicReturnTypeExtension.php, src/Extensions/DoctrineResultDynamicReturnTypeExtension.php, tests/DbaInferenceTest.php, tests/data/doctrine-dbal.php
refs https://github.com/staabm/phpstan-dba/issues/94
adds support for
- `Connection->query()`
- `Result->fetchNumeric()`
- `Result->fetchAssociative()`
- `Result->fetchAllNumeric()`
- `Result->fetchAllAssociative()`
- `Result->columnCount()`
=> Added initial Doctrine Dbal type inference

.phpunit-phpstan-dba.cache, src/QueryReflection/QueryReflection.php, src/Rules/PdoStatementExecuteMethodRule.php, tests/data/syntax-error-in-query.php
in hybrid apis which support both, prepared and regular statements, a user might configure `SyntaxErrorInQueryMethodRule` and `SyntaxErrorInPreparedStatementMethodRule` in tandem for a single method.
we need to make sure that `SyntaxErrorInQueryMethodRule` will not error for queries, which contain placeholders in this case.
refs https://github.com/staabm/phpstan-dba/issues/106#issuecomment-1014633286
=> Skip queries containing placeholders in `SyntaxErrorInQueryMethodRule`

.phpstan-dba.cache, .phpunit-phpstan-dba.cache, src/QueryReflection/QueryReflection.php, tests/data/pdo-prepare.php, tests/data/pdo.php, tests/data/syntax-error-in-prepared-statement.php
a real sql parser would be a better fit, but having a bit better support based on regex is progress nevertheless.
as a benefit we get some test-coverage for whatever solution we will implement in the longer term.
refs https://github.com/staabm/phpstan-dba/issues/123
=> make sure placeholders in query-string-data does not interfere with the analysis

src/QueryReflection/PlaceholderValidation.php, src/QueryReflection/QueryReflection.php, tests/data/syntax-error-in-prepared-statement.php
with proper sql parsing, we should better detect the placeholders and therefore could validate this query
refs https://github.com/staabm/phpstan-dba/issues/94#issuecomment-1016534736
=> don't report placeholder errors on non-SELECT statements for now

src/QueryReflection/ReflectionCache.php
should finally fix remaining race conditons in `RecordingQueryReflector`
closes https://github.com/staabm/phpstan-dba/issues/93
=> use shared read/write lock in ReflectionCache to prevent race conditions

.gitattributes, README.md
so they don't show up as diff in pull requests
https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
closes https://github.com/staabm/phpstan-dba/issues/155
=> mark phpstan-dba cache files as generated

.phpstan-dba.cache, .phpunit-phpstan-dba.cache, src/QueryReflection/QuerySimulation.php, tests/data/pdo.php, tests/data/syntax-error-in-prepared-statement.php
closes https://github.com/staabm/phpstan-dba/issues/175
=> support queries containing `OFFSET` after `LIMIT`

.phpstan-dba.cache, .phpunit-phpstan-dba.cache, src/QueryReflection/QueryReflection.php, tests/data/pdo-prepare.php
before this PR we allowed string-types in prepared statement context - even in the query simulation.
the special case for allowing string-types in prepared context does only work for the parameters given, separated from the actual statement. all string-types directly embedded in the query cannot be simulated
closes https://github.com/staabm/phpstan-dba/issues/196
=> prevent wrong type inference on queries containing string

README.md
refs https://github.com/staabm/phpstan-dba/issues/200
=> Readme: added note about mysql only support atm

src/Extensions/DoctrineConnectionFetchDynamicReturnTypeExtension.php
there is no `iterateAllNumeric` method in the api
=> doctrine-dbal: remove `iterateAllNumeric` from `Connection`

src/QueryReflection/QuerySimulation.php, tests/QuerySimulationTest.php
should fix 
```
Unresolvable Query: Cannot simulate parameter value for type:  
non-empty-array<int, int>. 
```
error
closes https://github.com/staabm/phpstan-dba/issues/176#issuecomment-1028318555
=> added minimal `IntersectionType` support

.phpstan-dba.cache, src/QueryReflection/MysqliQueryReflector.php, src/QueryReflection/QuerySimulation.php, tests/default/config/.phpstan-dba.cache, tests/default/config/.phpunit-phpstan-dba.cache, tests/default/data/doctrine-dbal.php, tests/stringify/config/.phpstan-dba.cache, tests/stringify/config/.phpunit-phpstan-dba.cache
refs https://github.com/staabm/phpstan-dba/issues/225#issuecomment-1029970147
ugly hack to make phpstan-dba not error on query which use date/datetime types with a placeholder.
I think in case we would have a proper sql parser, we could feed schema-type-dependent default values in case of strings.
=> Support simulation of date/dateime placeholders

.phpstan-dba.cache, src/Rules/SyntaxErrorInPreparedStatementMethodRule.php, tests/default/SyntaxErrorInPreparedStatementMethodRuleTest.php, tests/default/config/.phpstan-dba.cache, tests/default/config/.phpunit-phpstan-dba.cache, tests/default/data/syntax-error-in-prepared-statement.php, tests/stringify/config/.phpstan-dba.cache, tests/stringify/config/.phpunit-phpstan-dba.cache
refs https://github.com/staabm/phpstan-dba/issues/238
=> doctrine dbal: fix error detection in queries without args

src/QueryReflection/MysqliQueryReflector.php, src/TypeMapping/MySQLTypeMapper.php, src/TypeMapping/MysqliTypeMapper.php, src/TypeMapping/TypeMapper.php
Extract from https://github.com/staabm/phpstan-dba/pull/261
=> Extract & refactor mysqli TypeMapping

src/PdoReflection/PdoStatementReflection.php, src/QueryReflection/ExpressionFinder.php, src/Rules/PdoStatementExecuteMethodRule.php, tests/default/PdoStatementExecuteMethodRuleTest.php, tests/default/UnresolvablePdoStatementRuleTest.php, tests/default/data/pdo-stmt-execute-error.php, tests/default/data/pdo-stmt-execute.php, tests/default/data/unresolvable-pdo-statement.php
I think this adds the right pieces.
refs https://github.com/staabm/phpstan-dba/issues/199
=> Prototype support for bindValue/bindParam on PDOStatement

src/QueryReflection/RecordingQueryReflector.php, tests/default/config/.phpstan-dba.cache, tests/default/config/.phpunit-phpstan-dba.cache
Lets see whether this is still required
=> Remove recording workaround

src/Extensions/PdoQueryDynamicReturnTypeExtension.php, src/Extensions/PdoStatementFetchDynamicReturnTypeExtension.php, src/PdoReflection/PdoStatementReflection.php, src/QueryReflection/QueryReflector.php, tests/default/data/pdo-stmt-fetch.php, tests/rules/config/.phpstan-dba-mysqli.cache, tests/rules/config/.phpstan-dba-pdo.cache
it seems `PDO::FETCH_COLUMN` is not supported on `fetch()`.
its supported on `PDO->query()` though, but we might tackle this later
=> support `PDO::FETCH_COLUMN` in `fetchAll()`

src/Extensions/PdoStatementFetchDynamicReturnTypeExtension.php, tests/default/data/pdo-stmt-fetch.php, tests/rules/config/.phpstan-dba-mysqli.cache
@xPaw could you double check the types are what to expect?
initially I had the feeling this would not be supported, as I was not able to find it in the php.net manual
=> PDO: support `PDO::FETCH_COLUMN` in `fetch()`

config/extensions.neon, src/Extensions/PdoStatementFetchDynamicReturnTypeExtension.php, src/Extensions/PdoStatementFetchObjectDynamicReturnTypeExtension.php, src/PdoReflection/PdoStatementReflection.php, src/QueryReflection/QueryReflector.php, tests/default/Fixture/MyRowClass.php, tests/default/data/pdo-stmt-fetch.php, tests/rules/config/.phpstan-dba-mysqli.cache
=> PDO: Added `PDO::FETCH_CLASS` support on `fetch*()`, `fetchObject()`

src/QueryReflection/ReflectionCache.php
Fixes #298
I think there's a different type of cache order issue with `__set_state` which I suspect comes from using newer PHP version (I run php 8.1). All my caches are updated with `keyType` and `itemType` moves above `allArrays`, not really sure what's up with that.
I think `var_export` logic changed in what order it dumps properties?
EDIT: Yep, looks like it changed in PHP 8.1 - https://3v4l.org/Zt4tA
=> Stabilize error/result in cache

src/Extensions/PdoStatementFetchDynamicReturnTypeExtension.php, tests/default/data/pdo-stmt-fetch.php
Closes https://github.com/staabm/phpstan-dba/issues/305
=> `fetchAll(PDO::FETCH_KEY_PAIR)` has incorrect return type with an extra array

src/Extensions/PdoStatementFetchDynamicReturnTypeExtension.php, tests/rules/SyntaxErrorInQueryMethodRuleMysqliReflectorTest.php, tests/rules/SyntaxErrorInQueryMethodRulePdoReflectorTest.php, tests/rules/config/.phpstan-dba-mysqli.cache, tests/rules/config/.phpstan-dba-pdo.cache, tests/rules/config/.phpunit-phpstan-dba-mysqli.cache, tests/rules/config/.phpunit-phpstan-dba-pdo.cache, tests/rules/data/syntax-error-in-query-method.php
=> Use lowercase table name in tests to fix issue on Windows

src/QueryReflection/MysqliQueryReflector.php, src/QueryReflection/PdoQueryReflector.php
While the code already checks for `SELECT` statements only, this should enforce it on the database level.
For mysqli driver, it will throw "Cannot execute statement in a READ ONLY transaction" error, while in PDO in worse case it will roll back any of the changed data.
=> Use transactions when simulating queries

tests/default/data/pdo-mysql.php, tests/default/data/pdo-prepare.php
pgsql does not like these tests
```
1) staabm\PHPStanDba\Tests\DbaInferenceTest::testFileAsserts with data set "/home/runner/work/phpstan-dba/phpstan-dba/tests/default/data/pdo.php:158" ('type', '/home/runner/work/phpstan-dba...do.php', PHPStan\Type\Constant\ConstantStringType Object (...), PHPStan\Type\ObjectType Object (...), 158)
Expected type PDOStatement<array{adaid: int<-32768, 32767>}>, got type PDOStatement in /home/runner/work/phpstan-dba/phpstan-dba/tests/default/data/pdo.php on line 158.
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'PDOStatement<array{adaid: int<-32768, 32767>}>'
+'PDOStatement'
phar:///home/runner/work/phpstan-dba/phpstan-dba/vendor/phpstan/phpstan/phpstan.phar/src/Testing/TypeInferenceTestCase.php:56 …
```
=> moved mysql specific test into pdo-mysql

composer.json
Unless there is a special need for mysqli extension to be present, could this be moved to require-dev? Right now, there is also PdoQueryReflector available, but you still have to install mysqli extension to use it.
```sh
$ composer require --dev staabm/phpstan-dba
In PackageDiscoveryTrait.php line 308:
Package staabm/phpstan-dba has requirements incompatible with your PHP version, PHP extensions and Composer version:
- staabm/phpstan-dba 0.2.26 requires ext-mysqli * but it is not present.
```
=> Move ext-mysqli to require-dev

.phpstan-dba-mysqli.cache, .phpstan-dba-pdo-mysql.cache, src/Analyzer/QueryPlanQueryResolver.php, src/QueryReflection/QueryReflection.php, src/QueryReflection/QuerySimulation.php, src/Rules/QueryPlanAnalyzerRule.php, tests/default/config/.phpstan-dba-mysqli.cache, tests/default/config/.phpstan-dba-pdo-mysql.cache, tests/default/config/.phpunit-phpstan-dba-mysqli.cache, tests/default/config/.phpunit-phpstan-dba-pdo-mysql.cache, tests/defaultFetchAssoc/config/.phpstan-dba-mysqli.cache, tests/defaultFetchAssoc/config/.phpstan-dba-pdo-mysql.cache, tests/defaultFetchNumeric/config/.phpstan-dba-mysqli.cache, tests/defaultFetchNumeric/config/.phpstan-dba-pdo-mysql.cache, tests/rules/QueryPlanAnalyzerRuleTest.php, tests/rules/config/.phpstan-dba-mysqli.cache, tests/rules/config/.phpstan-dba-pdo-mysql.cache, tests/rules/config/.phpunit-phpstan-dba-mysqli.cache, tests/rules/config/.phpunit-phpstan-dba-pdo-mysql.cache, tests/rules/data/query-plan-analyzer.php, tests/stringify/config/.phpstan-dba-mysqli.cache, tests/stringify/config/.phpstan-dba-pdo-mysql.cache
The QueryPlanAnalyser does not strip trailing limits and offsets.
If limits and offsets are set via parameters it would escape the limits and offsets as strings.
This resulted in incorrect SQL being analysed.
=> Fix QueryPlanAnalyser with dynamic offset and limit params

tests/rules/SyntaxErrorInPreparedStatementMethodSubclassedRulePdoReflectorTest.php, tests/rules/SyntaxErrorInQueryFunctionRulePdoReflectorTest.php, tests/rules/SyntaxErrorInQueryMethodSubclassedRulePdoReflectorTest.php, tests/rules/config/.phpunit-phpstan-dba-mysqli.cache
Only query analyzer rule test is skipped for pgsql now, otherwise everything should have coverage with this.
Related to: #371
=> improve rules test coverage for pdo-pgsql

src/QueryReflection/ReflectionCache.php
should prevent inconsistent files when writing cache like
which turns into `Internal error: Internal error: syntax error, unexpected token "<", expecting end of file in file` errors
=> prevent race conditions while writing cache file

.phpstan-dba-mysqli.cache, .phpstan-dba-pdo-mysql.cache, src/QueryReflection/PdoMysqlQueryReflector.php, src/TypeMapping/MysqlTypeMapper.php, tests/default/config/.phpstan-dba-mysqli.cache, tests/default/config/.phpstan-dba-pdo-mysql.cache, tests/default/config/.phpunit-phpstan-dba-mysqli.cache, tests/default/config/.phpunit-phpstan-dba-pdo-mysql.cache, tests/default/data/pdo-mysql.php, tests/default/data/pdo-union-result.php, tests/defaultFetchAssoc/config/.phpstan-dba-mysqli.cache, tests/defaultFetchAssoc/config/.phpstan-dba-pdo-mysql.cache, tests/defaultFetchAssoc/config/.phpunit-phpstan-dba-mysqli.cache, tests/defaultFetchAssoc/config/.phpunit-phpstan-dba-pdo-mysql.cache, tests/defaultFetchNumeric/config/.phpstan-dba-mysqli.cache, tests/defaultFetchNumeric/config/.phpstan-dba-pdo-mysql.cache, tests/defaultFetchNumeric/config/.phpunit-phpstan-dba-mysqli.cache, tests/defaultFetchNumeric/config/.phpunit-phpstan-dba-pdo-mysql.cache, tests/rules/config/.phpstan-dba-mysqli.cache, tests/rules/config/.phpstan-dba-pdo-mysql.cache, tests/rules/config/.phpunit-phpstan-dba-mysqli.cache, tests/rules/config/.phpunit-phpstan-dba-pdo-mysql.cache, tests/schema.sql, tests/stringify/config/.phpstan-dba-mysqli.cache, tests/stringify/config/.phpstan-dba-pdo-mysql.cache, tests/stringify/config/.phpunit-phpstan-dba-mysqli.cache, tests/stringify/config/.phpunit-phpstan-dba-pdo-mysql.cache
=> [MySQL] Treat decimal as numeric-string

tests/rules/SyntaxErrorInQueryMethodRuleTest.php
missing part of https://github.com/staabm/phpstan-dba/pull/425
depends on https://github.com/phpstan/phpstan/issues/8058
atm the test fails because the rule involved runs into this early exit
https://github.com/staabm/phpstan-dba/blob/f60f559183d22df4394f943d7a6a2470e6941fe2/src/Rules/SyntaxErrorInQueryMethodRule.php#L47-L50
=> added `mysqli::execute_query()` support (php 8.2+ only)

src/PhpDoc/PhpDocUtil.php, src/QueryReflection/QueryReflection.php, tests/default/Fixture/Escaper.php, tests/default/data/pdo.php
conditional tainted input is not yet supported
https://psalm.dev/docs/security_analysis/avoiding_false_positives/#conditional-escaping-tainted-input
=> support non-conditional `@psalm-taint-escape sql`

src/QueryReflection/PdoQueryReflector.php
Before the change PHPStorm suggest the misspelling in auto-completion which is a bit annoying :grin:
=> Fix wrong deprecated annotation

.phpstan-dba-mysqli.cache, src/QueryReflection/QueryReflection.php, src/TypeMapping/MysqlTypeMapper.php, src/TypeMapping/PgsqlTypeMapper.php, tests/default/config/.phpunit-phpstan-dba-mysqli.cache, tests/rules/config/.phpunit-phpstan-dba-mysqli.cache, tests/stringify/config/.phpunit-phpstan-dba-mysqli.cache
lets keep the most precise types as long as possible.
stringification should be the last step. 
that way we can plug-in the sql parser in between without additional handling of stringification.
=> Stringify types later in the chain.

phpstan.neon.dist
to allow analyzing test files with `vendor/bin/phpstan analyze test.php --debug`
=> enable rules for project internal analysis

composer.json
we expect breaking changes with any sqlftw release, therefore for now whitelisting each manully
=> support sqlftw/sqlftw 0.1.7

src/Rules/DoctrineKeyValueStyleRule.php
prevents a exception while the rule is instantiated
```
$ vendor-bin/phpstan/vendor/bin/phpstan analyse -c deploy-phpstan.neon.dist --no-progress --debug
C:\dvl\Workspace\kunzmann\deploy.php
Uncaught staabm\PHPStanDba\DbaException: Reflector not initialized. Make sure a phpstan bootstrap file is configured which calls staabm\PHPStanDba\QueryReflection\QueryReflection::setupReflector(). in C:\dvl\Workspace\kunzmann\vendor-bin\phpstan\vendor\staabm\phpstan-dba\src\QueryReflection\QueryReflection.php:517
#0 C:\dvl\Workspace\kunzmann\vendor-bin\phpstan\vendor\staabm\phpstan-dba\src\QueryReflection\QueryReflection.php(66): staabm\PHPStanDba\QueryReflection\QueryReflection::reflector()
#1 C:\dvl\Workspace\kunzmann\vendor-bin\phpstan\vendor\staabm\phpstan-dba\src\Rules\DoctrineKeyValueStyleRule.p …
```
=> Create QueryReflection lazily to prevent eager creation of a database connection

src/Rules/DoctrineKeyValueStyleRule.php, tests/rules/DoctrineKeyValueStyleRuleTest.php
Table names must be constant strings, not literal strings.
As per https://github.com/staabm/phpstan-dba/issues/560#issuecomment-1464843621.
=> DoctrineKeyValueStyleRule: improve table error message

.phpstan-dba-mysqli.cache, .phpstan-dba-pdo-mysql.cache, phpstan-baseline.neon, phpstan.neon.dist, src/SchemaReflection/Join.php, src/SqlAst/ParserInference.php, src/SqlAst/QueryScope.php, tests/default/DbaInferenceTest.php, tests/default/config/.phpunit-phpstan-dba-mysqli.cache, tests/default/config/.phpunit-phpstan-dba-pdo-mysql.cache, tests/default/data/sql-ast-narrowing.php, tests/rules/config/.phpunit-phpstan-dba-mysqli.cache, tests/rules/config/.phpunit-phpstan-dba-pdo-mysql.cache
closes https://github.com/staabm/phpstan-dba/issues/527
=> Narrow types via join / join-condition

.phpstan-dba-mysqli.cache, .phpstan-dba-pdo-mysql.cache, src/SqlAst/ParserInference.php, src/UnresolvableAstInQueryException.php, tests/default/config/.phpunit-phpstan-dba-mysqli.cache, tests/default/config/.phpunit-phpstan-dba-pdo-mysql.cache, tests/default/data/sql-ast-narrowing.php
- support for multiple joins, up to now it was OK just for single join, this adds support for multiple
- skips AST for 
- cross joins
- queries with subqueries
- when condition is null (previous it was throwing runtime exception, now it just screams in debug)
The changes works fine for my codebase
=> support for cross joins. don't error on joins of subqueries

src/Rules/DoctrineKeyValueStyleRule.php, tests/rules/DoctrineKeyValueStyleRuleTest.php, tests/rules/data/doctrine-key-value-style.php
If any of the arguments (table name or parameter values) to the DoctrineKeyValueStyleRule methods are a union type, each subtype will now be checked independently.
Previously, union types would cause an error, because of the improper use of `instanceof *Type` checks. This is now fixed by using methods to get the constants, e.g. `getConstantStrings()`, as recommended in https://github.com/staabm/phpstan-dba/pull/564#discussion_r1133053061.
=> DoctrineKeyValueStyleRule: properly handle unions

src/Rules/DoctrineKeyValueStyleRule.php, tests/rules/DoctrineKeyValueStyleRuleTest.php, tests/rules/config/.phpunit-phpstan-dba-mysqli.cache, tests/rules/config/.phpunit-phpstan-dba-pdo-mysql.cache, tests/rules/data/doctrine-key-value-style.php
Using `$databaseType->isSuperTypeOf($valueType)` to check if the input value type matches the database column type was too strict. It was incorrectly raising errors for various legal scenarios, e.g.:
* Passing an integer to a float column.
* Passing a benevolent (float|int) to an int column.
The `accepts` method correctly handles these cases. Add extra logic for `MixedType`, since mixed types are always accepted.
NOTE: The `MixedType` case may be demoted to a debug-mode-only error, depending on the answer to https://github.com/staabm/phpstan-dba/pull/564#discussion_r1141097432.
=> DoctrineKeyValueStyeRule: allow int values in float columns

src/SqlAst/PositiveIntReturnTypeExtension.php, tests/sqlAst/data/sql-ast-narrowing.php, tests/stringify/data/ast-narrowed-stringify.php
Remove nullability from the PositiveIntReturnTypeExtension for the `COUNT` function case.
> If there are no matching rows, COUNT() returns 0. COUNT(NULL) returns 0.
(source: https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_count)
=> SQL AST: COUNT cannot return null

src/SqlAst/AvgReturnTypeExtension.php, src/SqlAst/MinMaxReturnTypeExtension.php, src/SqlAst/QueryScope.php, tests/sqlAst/config/.phpunit-phpstan-dba-mysqli.cache, tests/sqlAst/config/.phpunit-phpstan-dba-pdo-mysql.cache, tests/sqlAst/data/sql-ast-narrowing.php
Fix the avg return type extension using the following rules for its return value:
* `null` if the input is only null.
* `numeric-string` if non-null inputs are only integers.
* `float` if _any_ non-null input is a string.
Put min/max in their own return type extension, since their behavior is sufficiently different from avg. They return the input type, but if any input is a string, then the return value is stringified.
Closes #578.
=> SQL AST: min/max/avg improvements (#587)Co-authored-by: Markus Staab <maggus.staab@googlemail.com>

.gitattributes
This makes git consider the cache files as binary for the purposes of operations like `git diff`, `git log`, `git grep`, etc. As a result, only meaningful content is displayed in full, making development activities much more manageable.
See https://git-scm.com/docs/gitattributes#_marking_files_as_binary for motivation.
Thinking beyond this PR, it would be nice if the tests generated and replayed their own cache files, instead of manually managing them as part of the development workflow. Making sure the cache files are correct has been one of the bigger struggles for me, especially because there isn't a way to easily set up a local testing environment that is consistent with the GitHub Actions environment (I made my own Docker setup for local testing, but it has some friction with the GHA …
=> .gitattributes: remove diff attribute for cache files

src/SqlAst/ParserInference.php, src/SqlAst/QueryScope.php, tests/sqlAst/config/.phpunit-phpstan-dba-mysqli.cache, tests/sqlAst/config/.phpunit-phpstan-dba-pdo-mysql.cache, tests/sqlAst/data/sql-ast-narrowing.php
The WHERE condition of a SQL statement may narrow the type returned from a table. We can account for this when getting the type of each selected column.
Currently, the only implemented conditions are `IS NOT NULL` and `IS NULL`. This can be expanded in the future to support other binary operators and comparison operators.
Since the WHERE condition can narrow selections that are implicitly specified with an asterisk, we now expand the asterisk to an explicit list of columns so that we can perform the AST-based type resolution on them.
=> SQL AST: narrow result types with WHERE condition

.github/dependabot.yml
Versioning strategies are not supported for actions.
From https://github.com/staabm/phpstan-dba/pull/614#issuecomment-1657066369
=> Remove actions versioning strategy

.github/workflows/phpstan.yml, .github/workflows/tests.yml
inspired by https://github.com/staabm/phpstan-dba/pull/613
extracted the parts which actually fix the current failling builds.
refactoring the matrix, like done in #613 should be a separate PR.
Co-authored-by: @szepeviktor
=> Fix MariaDB health check

.github/workflows/phpstan.yml, composer.json, phpstan.neon.dist
- Added a real 3×2×1×1 matrix + 3 "includes"
- Move database options to `db-options`
- PHP 8.0 + MariaDB was excluded - Should I exclude it now?
=> Add a real matrix to Static analysis workflow

phpstan.neon.dist
=> Readd unused-public configuration to phpstan.neon.dist

config/Mysqli.stub
for now we remove support for `mysqli_fetch_object` in phpstan-dba to make phpstan-dba work for all other usescases again.
in a followup I will try to get rid of the stubs in phpstan-dba so we don't depend on changes of stubs in phpstans-src
closes https://github.com/staabm/phpstan-dba/issues/631
=> Fix "$result contains generic type mysqli_result<mixed> but class mysqli_result is not generic"

.github/workflows/phpstan.yml, .github/workflows/tests-postgres.yml, .github/workflows/tests.yml
currently we don't support 4.x - PRs welcome ;)
phpstan-dba should work for doctrine/dbal 4.x methods which are backwards compatible to 3.x though, therefore we don't declare a composer conflict with doctrine/dbal 4.x
=> Fix Doctrine Tests

.phpstan-dba-mysqli.cache, .phpstan-dba-pdo-mysql.cache, src/QueryReflection/QueryReflection.php, tests/rules/SyntaxErrorInQueryFunctionRuleTest.php, tests/rules/SyntaxErrorInQueryMethodRuleTest.php, tests/rules/config/.phpunit-phpstan-dba-mysqli.cache, tests/rules/config/.phpunit-phpstan-dba-pdo-mysql.cache, tests/rules/data/pdo-stmt-execute-error.php
Hi 👋 🙂 
I encountered an edge case with the Regex currently used to parse placeholders.
```
payload ->> '$."value-1"' = :value1
OR
payload ->> '$."value-2"' = :value2
```
ℹ️  `"` are needed here to escape the `-` special character in the field's name
The problem with the current `(["\'])([^"\']*\1)` regex is that it tries to exclude `'` **AND** `"` in the middle of a _string_. If this is a simply quoted string we should exclude only simple quotes. 
I found a way to negate a backreference in [stackoverflow](https://stackoverflow.com/a/8057827).
~Unfortunately, I totally failed to run tests locally, so I didn't add corresponding test... but I would love to if you have some helping instructions~ 
~[Edit] it seems that locally I got the same errors encountered by the CI, so maybe the issue is …
=> Support nested quotes

src/QueryReflection/QueryReflection.php, tests/rules/data/pdo-stmt-execute-error.php
Fix #657 
In #651, I included the `.` to mach _any_ character. Actually, it matches _any_ character except _newline_ 😅 
Here are [several workarounds from stackoverflow](https://stackoverflow.com/questions/8055727/negating-a-backreference-in-regular-expressions/8057827#8057827)
I choose to replace `.` by `(?s:.)`, because it locally changes the regex flag to also match newline character, without adding too much noise....
Added a test 🎁
=> Fix placeholders detection with multiline strings

src/QueryReflection/QuerySimulation.php, tests/default/data/pdo-prepare.php, tests/rules/UnresolvableQueryMethodRuleTest.php, tests/rules/data/bug-676.php
closes https://github.com/staabm/phpstan-dba/issues/676#issuecomment-2441079671
=> Support `iterable` typed parameter

composer.json, phpstan.neon.dist
This reverts commit f9cd010a7e8c46b11aab37e3f056dbd0fd908bf7.
re-enable after the tomasvotruba/unused-public extension works with PHPStan 2.x
=> Revert "Disable tomasvotruba/unused-public for now"

src/PdoReflection/PdoStatementObjectType.php, tests/default/data/pdo-fetch-types.php
closes https://github.com/staabm/phpstan-dba/issues/748
=> Fix type when using \PDO::FETCH_OBJ on iteration

src/QueryReflection/PlaceholderValidation.php, src/QueryReflection/QueryReflection.php, tests/rules/data/syntax-error-in-prepared-statement.php
don't validate parameters against partial-known queries
=> Prevent false-positives in placeholder validation
