staabm/phpstan-dba

- src/QueryReflection/RecordingQueryReflector.php
- src/QueryReflection/ReflectionCache.php
- src/QueryReflection/ReplayQueryReflector.php
> refactor ReflectionCache

- config/Mysqli.stub
- src/QueryReflection/MysqliQueryReflector.php
mysqli throws exceptions by default only since php 8.1
https://www.php.net/manual/en/changelog.mysqli.php
> enable mysqli exception throwing on php < 8.1

- composer.json
see https://github.com/staabm/phpstan-dba/blob/88cdf9dec74252e032609c15d4b9a73a73d8ae82/README.md?plain=1#L125
> run phpstan always in debug mode for now

- src/DbaException.php
- src/Extensions/DeployerRunMysqlQueryDynamicReturnTypeExtension.php
- src/Extensions/MysqliQueryDynamicReturnTypeExtension.php
- src/Extensions/PdoQueryDynamicReturnTypeExtension.php
- src/QueryReflection/QueryReflection.php
- src/Rules/SyntaxErrorInQueryFunctionRule.php
- src/Rules/SyntaxErrorInQueryMethodRule.php
preparation for named/numeric parameter templates
> refactoring

- config/extensions.neon
- src/Extensions/PdoStatementColumnCountDynamicReturnTypeExtension.php
- tests/DbaInferenceTest.php
- tests/data/pdo-column-count.php
since we have all information at hand at analysis time, we can easily make `columnCount` return an analysis-time integer constant
> support `PDOStatement->columnCount()`

- src/Extensions/MysqliQueryDynamicReturnTypeExtension.php
> Refactor `MysqliQueryDynamicReturnTypeExtension`

- src/PdoReflection/PdoStatementReflection.php
refs https://github.com/staabm/phpstan-dba/issues/51#issuecomment-1009424313
atm we don't use astral, therefore drop the dep for now.
> remove depedency on symplify/astral

- composer.json
- src/PdoReflection/PdoStatementReflection.php
no longer used it seems
closes https://github.com/staabm/phpstan-dba/issues/51
> remove dependency on rector

- .github/workflows/phpstan.yml
- .github/workflows/tests.yml
- .phpstan-dba.cache
- .phpunit-phpstan-dba.cache
- src/QueryReflection/MysqliQueryReflector.php
- tests/SyntaxErrorInPreparedStatementMethodRuleTest.php
- tests/SyntaxErrorInQueryFunctionRuleTest.php
- tests/SyntaxErrorInQueryMethodRuleTest.php
refs https://github.com/staabm/phpstan-dba/issues/69#issuecomment-1010279802
> added mariadb coverage to github actions

- README.md
- composer.json
- src/QueryReflection/ReflectionCache.php
closes https://github.com/staabm/phpstan-dba/issues/93
> make `RecordingQueryReflector` work, without the need to pass `--debug`

- src/QueryReflection/ReflectionCache.php
should reduce unnecessary cache writes. its still not thread-safe but should work for most cases
refs https://github.com/staabm/phpstan-dba/issues/93
> more fine grained `ReflectionCache` change-detection

- src/QueryReflection/ReflectionCache.php
closes https://github.com/staabm/phpstan-dba/issues/93
> reduce the risk of possible concurrency issues in `ReflectionCache`

- .phpstan-dba.cache
- .phpunit-phpstan-dba.cache
- composer.json
- config/dba.neon
- tests/SyntaxErrorInQueryMethodRuleTest.php
- tests/data/syntax-error-in-query.php
Based on https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/data-retrieval-and-manipulation.html#data-retrieval-and-manipulation
refs https://github.com/staabm/phpstan-dba/issues/94
> Support `\Doctrine\DBAL\Connection->query()` syntax error checking

- tests/data/syntax-error-in-query.php
Covering https://github.com/staabm/phpstan-dba/issues/106#issuecomment-1014803881
> Added testcase

- .phpstan-dba.cache
- .phpunit-phpstan-dba.cache
- tests/data/pdo.php
closes https://github.com/staabm/phpstan-dba/issues/122
it already works like expected
> added left join coverage

- .phpstan-dba.cache
- .phpunit-phpstan-dba.cache
- src/QueryReflection/MysqliQueryReflector.php
- tests/data/pdo.php
- tests/schema.sql
closes https://github.com/staabm/phpstan-dba/issues/125
> cover more mysql types

- .phpunit-phpstan-dba.cache
- src/QueryReflection/ReflectionCache.php
closes https://github.com/staabm/phpstan-dba/issues/93
> use separate lock-file to prevent race conditions

- .phpstan-dba.cache
- .phpunit-phpstan-dba.cache
- src/QueryReflection/QuerySimulation.php
- tests/data/pdo-prepare.php
- tests/data/syntax-error-in-prepared-statement.php
refs https://github.com/staabm/phpstan-dba/issues/94#issuecomment-1016534736
should fix 
```
Uncaught staabm\PHPStanDba\DbaException: Unexpected expression type PHPStan\Type\ArrayType in /home/mt/www/5.7dev/vendor/staabm/phpstan-dba/src/QueryReflection/QuerySimulation.php:72
#0 /home/mt/www/5.7dev/vendor/staabm/phpstan-dba/src/QueryReflection/QueryReflection.php(181): staabm\PHPStanDba\QueryReflection\QuerySimulation::simulateParamValueType()
#1 /home/mt/www/5.7dev/vendor/staabm/phpstan-dba/src/Rules/SyntaxErrorInPreparedStatementMethodRule.php(100): staabm\PHPStanDba\QueryReflection\QueryReflection->resolveParameters()
#2 /home/mt/www/5.7dev/vendor/staabm/phpstan-dba/src/Rules/SyntaxErrorInPreparedStatementMethodRule.php(80): staabm\PHPStanDba\Rules\SyntaxErrorInPreparedStatementMethodRul …
```
> support array-bound values to support IN(:param) expressions

- .phpstan-dba.cache
- .phpunit-phpstan-dba.cache
- phpstan.neon.dist
- src/QueryReflection/QuerySimulation.php
- tests/data/pdo-prepare.php
- tests/data/syntax-error-in-prepared-statement.php
Closes https://github.com/staabm/phpstan-dba/issues/156
> Don't error on prepared statements containing unspecified arrays

- src/QueryReflection/ReflectionCache.php
closes https://github.com/staabm/phpstan-dba/issues/154
> try to create cache file if none exist

- src/Rules/PdoStatementExecuteMethodRule.php
- src/Rules/SyntaxErrorInPreparedStatementMethodRule.php
- src/Rules/SyntaxErrorInQueryFunctionRule.php
- src/Rules/SyntaxErrorInQueryMethodRule.php
- tests/data/unresolvable-pdo-statement.php
- tests/data/unresolvable-query-in-function.php
- tests/data/unresolvable-query-in-method.php
- tests/data/unresolvable-statement.php
don't report queries which are completly unknown as unresolvable
followup to https://github.com/staabm/phpstan-dba/pull/164
> cover more unresolvable-query cases

- config/dba.neon
adds query syntax and prepraed statement validation
> doctrine-dbal: cover all `EntityManagerInterface` query methods

- .phpstan-dba.cache
- .phpunit-phpstan-dba.cache
- src/QueryReflection/QuerySimulation.php
- tests/data/pdo.php
- tests/data/syntax-error-in-prepared-statement.php
see https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html
> support queries which acquire read locks

- config/dba.neon
closes https://github.com/staabm/phpstan-dba/issues/177
> disable generic type check for stubbed generic classes

- .phpstan-dba.cache
- .phpunit-phpstan-dba.cache
- src/QueryReflection/PlaceholderValidation.php
- tests/data/syntax-error-in-prepared-statement.php
depends on https://github.com/phpstan/phpstan/issues/6439
closes https://github.com/staabm/phpstan-dba/issues/174
> support optional parameter values

- .phpstan-dba.cache
- .phpunit-phpstan-dba.cache
- config/extensions.neon
- src/Extensions/DoctrineConnectionFetchDynamicReturnTypeExtension.php
- tests/data/doctrine-dbal.php
refs https://github.com/staabm/phpstan-dba/issues/94
> doctrine-dbal: added type inferrence `fetchAssocitive()` and `fetchNumeric()` on `Connection`

- .phpstan-dba.cache
- .phpunit-phpstan-dba.cache
- src/DoctrineReflection/DoctrineReflection.php
- src/Extensions/DoctrineConnectionFetchDynamicReturnTypeExtension.php
- src/Extensions/DoctrineResultDynamicReturnTypeExtension.php
- tests/data/doctrine-dbal.php
> implement more doctrine dbal methods

- .phpstan-dba.cache
- .phpunit-phpstan-dba.cache
- src/DoctrineReflection/DoctrineReflection.php
- src/Extensions/DoctrineConnectionFetchDynamicReturnTypeExtension.php
- src/QueryReflection/QueryReflector.php
- tests/data/doctrine-dbal.php
> doctrine-dbal: implement `Connection->fetchOne()`

- .phpstan-dba.cache
- .phpunit-phpstan-dba.cache
- src/DoctrineReflection/DoctrineReflection.php
- src/Extensions/DoctrineConnectionFetchDynamicReturnTypeExtension.php
- src/Extensions/DoctrineResultDynamicReturnTypeExtension.php
- src/QueryReflection/QueryReflector.php
- tests/data/doctrine-dbal.php
> doctrine-dbal: implement `Connection->fetchFirstColumn()`, `Result->fetchFirstColumn()`

- src/DoctrineReflection/DoctrineReflection.php
- src/Extensions/DoctrineConnectionFetchDynamicReturnTypeExtension.php
- tests/data/doctrine-dbal.php
> doctrine-dbal: implement `Connection->iterateColumn()`

- .phpstan-dba.cache
- src/Extensions/DoctrineConnectionFetchDynamicReturnTypeExtension.php
- tests/data/doctrine-dbal.php
> doctrine-dbal: doctrine-dbal: implement `fetchAllKeyValue` & `iterateKeyValue` on `Connection`

- .github/workflows/phpstan.yml
- src/QueryReflection/MysqliQueryReflector.php
skip bool constants like MYSQLI_IS_MARIADB
> fix query reflection on mariadb with latest php-src

- .phpstan-dba.cache
- src/Extensions/DoctrineConnectionExecuteQueryDynamicReturnTypeExtension.php
- src/Extensions/DoctrineConnectionFetchDynamicReturnTypeExtension.php
- tests/default/data/doctrine-dbal.php
- tests/stringify/config/.phpstan-dba.cache
- tests/stringify/config/.phpunit-phpstan-dba.cache
refs https://github.com/staabm/phpstan-dba/issues/238
> doctrine dbal: support statements without args

- src/QueryReflection/QuerySimulation.php
- tests/default/config/.phpstan-dba.cache
- tests/default/config/.phpunit-phpstan-dba.cache
- tests/stringify/config/.phpstan-dba.cache
- tests/stringify/config/.phpunit-phpstan-dba.cache
Otherwise the cache would only work for one day
> Use fixed date in QuerySimulation

- bootstrap.php
- tests/ReflectorFactory.php
refs https://github.com/staabm/phpstan-dba/issues/267#issuecomment-1034789852
> Added env vars for Testsuite db-credentials, re-use ReflectorFactory in /bootstrap.php

- .phpstan-dba.cache
- src/Rules/SyntaxErrorInPreparedStatementMethodRule.php
- src/Rules/SyntaxErrorInQueryMethodRule.php
- tests/default/Fixture/BaseQueryClass.php
- tests/default/Fixture/MySubClass.php
- tests/default/SyntaxErrorInPreparedStatementMethodSubclassedRuleTest.php
- tests/default/SyntaxErrorInQueryMethodSubclassedRuleTest.php
- tests/default/config/.phpunit-phpstan-dba.cache
- tests/default/config/subclassed-method-rule.neon
- tests/default/data/syntax-error-in-method-subclassed.php
Sorry, I haven't much time currently, so I changed this via github and without any tests. :|
> SyntaxErrorInQueryMethodRule: allow abstract classes in "classMethods"

- .phpstan-dba-mysqli.cache
- .phpstan-dba-pdo.cache
- src/Extensions/PdoPrepareDynamicReturnTypeExtension.php
- src/Extensions/PdoQueryDynamicReturnTypeExtension.php
- src/Extensions/PdoStatementExecuteTypeSpecifyingExtension.php
- src/Extensions/PdoStatementFetchDynamicReturnTypeExtension.php
- src/PdoReflection/PdoStatementReflection.php
- src/QueryReflection/QueryReflection.php
- tests/default/DbaInferenceTest.php
- tests/default/config/.phpstan-dba-mysqli.cache
- tests/default/config/.phpstan-dba-pdo.cache
- tests/default/config/.phpunit-phpstan-dba-mysqli.cache
- tests/default/config/.phpunit-phpstan-dba-pdo.cache
- tests/default/data/pdo-union-result.php
- tests/rules/config/.phpstan-dba-mysqli.cache
- tests/rules/config/.phpstan-dba-pdo.cache
- tests/rules/config/.phpunit-phpstan-dba-mysqli.cache
- tests/rules/config/.phpunit-phpstan-dba-pdo.cache
refs https://github.com/staabm/phpstan-dba/issues/276#issuecomment-1038046488
> implement type inference for union-types in sql queries

- .phpstan-dba-mysqli.cache
- tests/default/data/pdo-union-result.php
refs https://github.com/staabm/phpstan-dba/pull/290
> union query `PDO->query()` test coverage

- src/DoctrineReflection/DoctrineReflection.php
- src/PdoReflection/PdoStatementReflection.php
- tests/default/data/pdo-stmt-fetch.php
- tests/rules/config/.phpstan-dba-mysqli.cache
> PDO: added `PDO::FETCH_KEY_PAIR` support

- .phpstan-dba-mysqli.cache
- .phpstan-dba-pdo.cache
- src/PdoReflection/PdoStatementReflection.php
- tests/default/data/pdo-fetch-types.php
- tests/default/data/pdo-stmt-fetch.php
- tests/rules/config/.phpunit-phpstan-dba-pdo.cache
> PDO: implement `PDO::FETCH_OBJ`

- config/PdoStatement.stub
- src/Extensions/PdoStatementSetFetchModeTypeSpecifyingExtension.php
- src/PdoReflection/PdoStatementObjectType.php
- src/PdoReflection/PdoStatementReflection.php
- tests/default/data/pdo-fetch-types.php
- tests/default/data/pdo-prepare.php
- tests/default/data/pdo-quote.php
- tests/default/data/pdo-stmt-execute.php
- tests/default/data/pdo-stmt-fetch.php
- tests/default/data/pdo-stmt-set-fetch-mode.php
- tests/default/data/pdo.php
- tests/default/data/query-alias.php
- tests/defaultFetchAssoc/data/modes.php
- tests/defaultFetchNumeric/data/modes.php
- tests/stringify/data/stringify.php
refs https://github.com/staabm/phpstan-dba/issues/282
> added `PdoStatementObjectType`

- src/Extensions/PdoStatementColumnCountDynamicReturnTypeExtension.php
utilize `PdoStatementObjectType`
> simplify `PdoStatementColumnCountDynamicReturnTypeExtension`

- src/DoctrineReflection/DoctrineReflection.php
- src/DoctrineReflection/DoctrineResultObjectType.php
- src/DoctrineReflection/DoctrineStatementObjectType.php
- src/Extensions/DoctrineResultDynamicReturnTypeExtension.php
refs https://github.com/staabm/phpstan-dba/issues/282
> added doctrine-ObjectTypes

- src/Extensions/MysqliQueryDynamicReturnTypeExtension.php
- src/MysqliReflection/MysqliResultObjectType.php
refs https://github.com/staabm/phpstan-dba/issues/282
> added `MysqliResultObjectType`

- .phpstan-dba-mysqli.cache
- tests/default/config/.phpstan-dba-mysqli.cache
- tests/default/config/.phpstan-dba-pdo.cache
- tests/default/config/.phpunit-phpstan-dba-mysqli.cache
- tests/default/config/.phpunit-phpstan-dba-pdo.cache
- tests/default/data/doctrine-dbal.php
- tests/default/data/mysqli.php
- tests/default/data/pdo-fetch-types.php
- tests/default/data/pdo.php
- tests/default/data/query-alias.php
- tests/defaultFetchAssoc/config/.phpstan-dba-mysqli.cache
- tests/defaultFetchAssoc/config/.phpstan-dba-pdo.cache
- tests/defaultFetchAssoc/config/.phpunit-phpstan-dba-mysqli.cache
- tests/defaultFetchAssoc/config/.phpunit-phpstan-dba-pdo.cache
- tests/defaultFetchAssoc/data/modes.php
- tests/defaultFetchNumeric/config/.phpstan-dba-mysqli.cache
- tests/defaultFetchNumeric/config/.phpstan-dba-pdo.cache
- tests/defaultFetchNumeric/config/.phpunit-phpstan-dba-mysqli.cache
- tests/defaultFetchNumeric/config/.phpunit-phpstan-dba-pdo.cache
- tests/defaultFetchNumeric/data/modes.php
> tests: use more portable types

- config/PdoStatement.stub
- src/QueryReflection/PdoQueryReflector.php
Requires https://github.com/phpstan/phpstan/issues/6743
> Remove ignore-next-line

- .phpstan-dba-mysqli.cache
- .phpstan-dba-pdo.cache
- src/QueryReflection/QueryReflection.php
- tests/default/config/.phpstan-dba-mysqli.cache
- tests/default/config/.phpstan-dba-pdo.cache
- tests/default/config/.phpunit-phpstan-dba-mysqli.cache
- tests/default/config/.phpunit-phpstan-dba-pdo.cache
- tests/defaultFetchAssoc/config/.phpstan-dba-mysqli.cache
- tests/defaultFetchAssoc/config/.phpstan-dba-pdo.cache
- tests/defaultFetchAssoc/config/.phpunit-phpstan-dba-mysqli.cache
- tests/defaultFetchAssoc/config/.phpunit-phpstan-dba-pdo.cache
- tests/defaultFetchNumeric/config/.phpstan-dba-mysqli.cache
- tests/defaultFetchNumeric/config/.phpstan-dba-pdo.cache
- tests/defaultFetchNumeric/config/.phpunit-phpstan-dba-mysqli.cache
- tests/defaultFetchNumeric/config/.phpunit-phpstan-dba-pdo.cache
- tests/rules/config/.phpstan-dba-mysqli.cache
- tests/rules/config/.phpstan-dba-pdo.cache
- tests/rules/config/.phpunit-phpstan-dba-mysqli.cache
- tests/rules/config/.phpunit-phpstan-dba-pdo.cache
- tests/rules/data/pdo-stmt-execute-error.php
- tests/stringify/config/.phpstan-dba-mysqli.cache
- tests/stringify/config/.phpstan-dba-pdo.cache
- tests/stringify/config/.phpunit-phpstan-dba-mysqli.cache
- tests/stringify/config/.phpunit-phpstan-dba-pdo.cache
closes https://github.com/staabm/phpstan-dba/issues/336
[fix by Jordi](https://github.com/staabm/phpstan-dba/issues/336#issuecomment-1106449280) - thank you so much.
> placeholder count is not correct when quotes involved

- .phpstan-dba-mysqli.cache
- .phpstan-dba-pdo.cache
- src/QueryReflection/QuerySimulation.php
- tests/default/config/.phpstan-dba-mysqli.cache
- tests/default/config/.phpstan-dba-pdo.cache
- tests/default/config/.phpunit-phpstan-dba-mysqli.cache
- tests/default/config/.phpunit-phpstan-dba-pdo.cache
- tests/default/data/pdo.php
- tests/rules/config/.phpstan-dba-mysqli.cache
- tests/rules/config/.phpstan-dba-pdo.cache
- tests/rules/config/.phpunit-phpstan-dba-mysqli.cache
- tests/rules/config/.phpunit-phpstan-dba-pdo.cache
see https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html#innodb-locking-reads-nowait-skip-locked
closes https://github.com/staabm/phpstan-dba/issues/340
> support mysql read concurrency with NOWAIT and SKIP LOCKED

- .phpstan-dba-mysqli.cache
- .phpstan-dba-pdo.cache
- tests/default/DbaInferenceTest.php
- tests/default/data/pdo-mysql.php
- tests/default/data/pdo-stmt-execute.php
- tests/default/data/pdo.php
separated tests which are not pgsql compatible
backported from https://github.com/staabm/phpstan-dba/pull/328
> separated non-pgsql test

- composer.json
- src/Extensions/MysqliQueryDynamicReturnTypeExtension.php
- src/Extensions/PdoQueryDynamicReturnTypeExtension.php
- src/Extensions/PdoStatementExecuteTypeSpecifyingExtension.php
- tests/default/config/.phpunit-phpstan-dba-mysqli.cache
- tests/defaultFetchAssoc/config/.phpunit-phpstan-dba-mysqli.cache
- tests/defaultFetchNumeric/config/.phpunit-phpstan-dba-mysqli.cache
- tests/rules/PdoStatementExecuteMethodRuleTest.php
- tests/rules/SyntaxErrorInPreparedStatementMethodRuleMysqliReflectorTest.php
- tests/rules/SyntaxErrorInPreparedStatementMethodRulePdoReflectorTest.php
- tests/rules/SyntaxErrorInPreparedStatementMethodSubclassedRuleMysqliReflectorTest.php
- tests/rules/SyntaxErrorInPreparedStatementMethodSubclassedRulePdoReflectorTest.php
- tests/rules/SyntaxErrorInQueryFunctionRuleMysqliReflectorTest.php
- tests/rules/SyntaxErrorInQueryFunctionRulePdoReflectorTest.php
- tests/rules/SyntaxErrorInQueryMethodRuleMysqliReflectorTest.php
- tests/rules/SyntaxErrorInQueryMethodRulePdoReflectorTest.php
- tests/rules/SyntaxErrorInQueryMethodSubclassedRuleMysqliReflectorTest.php
- tests/rules/SyntaxErrorInQueryMethodSubclassedRulePdoReflectorTest.php
- tests/rules/UnresolvablePdoStatementRuleTest.php
- tests/rules/UnresolvablePreparedStatementRuleTest.php
- tests/rules/UnresolvableQueryFunctionRuleTest.php
- tests/rules/UnresolvableQueryMethodRuleTest.php
- tests/rules/config/.phpunit-phpstan-dba-mysqli.cache
- tests/stringify/config/.phpunit-phpstan-dba-mysqli.cache
> drop symplify/phpstan-extensions dependency

- .phpstan-dba-mysqli.cache
- .phpstan-dba-pdo.cache
- src/QueryReflection/QueryReflection.php
- src/QueryReflection/ReflectionCache.php
- tests/default/config/.phpstan-dba-mysqli.cache
- tests/default/config/.phpstan-dba-pdo.cache
- tests/default/config/.phpunit-phpstan-dba-mysqli.cache
- tests/default/config/.phpunit-phpstan-dba-pdo.cache
- tests/defaultFetchAssoc/config/.phpstan-dba-mysqli.cache
- tests/defaultFetchAssoc/config/.phpstan-dba-pdo.cache
- tests/defaultFetchAssoc/config/.phpunit-phpstan-dba-mysqli.cache
- tests/defaultFetchAssoc/config/.phpunit-phpstan-dba-pdo.cache
- tests/defaultFetchNumeric/config/.phpstan-dba-mysqli.cache
- tests/defaultFetchNumeric/config/.phpstan-dba-pdo.cache
- tests/defaultFetchNumeric/config/.phpunit-phpstan-dba-mysqli.cache
- tests/defaultFetchNumeric/config/.phpunit-phpstan-dba-pdo.cache
- tests/rules/config/.phpstan-dba-mysqli.cache
- tests/rules/config/.phpstan-dba-pdo.cache
- tests/rules/config/.phpunit-phpstan-dba-mysqli.cache
- tests/rules/config/.phpunit-phpstan-dba-pdo.cache
- tests/stringify/config/.phpstan-dba-mysqli.cache
- tests/stringify/config/.phpstan-dba-pdo.cache
- tests/stringify/config/.phpunit-phpstan-dba-mysqli.cache
- tests/stringify/config/.phpunit-phpstan-dba-pdo.cache
followup to https://github.com/staabm/phpstan-dba/pull/374
> normalize EOL also in prepared queries

- .phpstan-dba-mysqli.cache
- .phpstan-dba-pdo.cache
- src/QueryReflection/QueryReflection.php
- src/QueryReflection/ReflectionCache.php
- tests/default/config/.phpstan-dba-mysqli.cache
- tests/default/config/.phpstan-dba-pdo.cache
- tests/default/config/.phpunit-phpstan-dba-mysqli.cache
- tests/default/config/.phpunit-phpstan-dba-pdo.cache
- tests/defaultFetchAssoc/config/.phpstan-dba-mysqli.cache
- tests/defaultFetchAssoc/config/.phpstan-dba-pdo.cache
- tests/defaultFetchAssoc/config/.phpunit-phpstan-dba-mysqli.cache
- tests/defaultFetchAssoc/config/.phpunit-phpstan-dba-pdo.cache
- tests/defaultFetchNumeric/config/.phpstan-dba-mysqli.cache
- tests/defaultFetchNumeric/config/.phpstan-dba-pdo.cache
- tests/defaultFetchNumeric/config/.phpunit-phpstan-dba-mysqli.cache
- tests/defaultFetchNumeric/config/.phpunit-phpstan-dba-pdo.cache
- tests/rules/config/.phpstan-dba-mysqli.cache
- tests/rules/config/.phpstan-dba-pdo.cache
- tests/rules/config/.phpunit-phpstan-dba-mysqli.cache
- tests/rules/config/.phpunit-phpstan-dba-pdo.cache
- tests/stringify/config/.phpstan-dba-mysqli.cache
- tests/stringify/config/.phpstan-dba-pdo.cache
- tests/stringify/config/.phpunit-phpstan-dba-mysqli.cache
- tests/stringify/config/.phpunit-phpstan-dba-pdo.cache
followup to followup to https://github.com/staabm/phpstan-dba/pull/374
> trim queries for cross-OS compat

- .github/workflows/phpstan.yml
see https://github.com/phpstan/phpstan/discussions/7311
> added build job against phpstan@dev

- .phpstan-dba-mysqli.cache
- .phpstan-dba-pdo-mysql.cache
- composer.json
- config/extensions.neon
- src/Ast/ExpressionFinder.php
- src/Ast/NodeConnectingVisitor.php
- src/Ast/PreviousConnectingVisitor.php
- src/PdoReflection/PdoStatementReflection.php
- src/QueryReflection/QueryReflection.php
- tests/default/config/.phpstan-dba-mysqli.cache
- tests/default/config/.phpstan-dba-pdo-mysql.cache
- tests/default/config/.phpunit-phpstan-dba-mysqli.cache
- tests/default/config/.phpunit-phpstan-dba-pdo-mysql.cache
- tests/rules/config/.phpstan-dba-mysqli.cache
- tests/rules/config/.phpstan-dba-pdo-mysql.cache
- tests/rules/config/.phpunit-phpstan-dba-mysqli.cache
- tests/rules/config/.phpunit-phpstan-dba-pdo-mysql.cache
- tests/stringify/config/.phpstan-dba-mysqli.cache
- tests/stringify/config/.phpstan-dba-pdo-mysql.cache
see 
- https://github.com/phpstan/phpstan/discussions/7433
- https://phpstan.org/blog/preprocessing-ast-for-custom-rules
> improve compatibility with phpstan@bleedingEdge

- .github/workflows/phpstan.yml
- .github/workflows/tests.yml
waiting for phpunit php 8.2 compat (actually its transitive dependencies)
https://github.com/sebastianbergmann/phpunit/issues/5033
> cover php 8.2 in CI

- src/QueryReflection/QueryReflection.php
refs https://github.com/phpstan/phpstan/issues/8035
> better error message on setup problems

- src/QueryReflection/QueryReflection.php
- tests/default/data/inference-placeholder.php
followup to https://github.com/staabm/phpstan-dba/pull/413/
> support `@phpstandba-inference-placeholder` on static method calls

- src/QueryReflection/QueryReflection.php
- tests/default/data/pdo.php
at best reviewed with whitespaces disabled: https://github.com/staabm/phpstan-dba/pull/433/files?w=1
> support encapsed strings

- src/QueryReflection/QueryReflection.php
- tests/default/data/inference-placeholder.php
inspired by https://github.com/FriendsOfREDAXO/rexstan/pull/155
> support `@phpstandba-inference-placeholder` on calls via variable

- src/PhpDoc/PhpDocUtil.php
for global code like
```
$x = new X();
$x->insert($_GET);
```
> support out-of-class MethodCalls in PhpDocUtil

- src/PhpDoc/PhpDocUtil.php
- tests/default/data/inference-placeholder.php
closes https://github.com/staabm/phpstan-dba/issues/439
see https://regexr.com/6vp8e
> fix phpdoc parsing with whitespaces/contents after values

- .github/workflows/tests.yml
- .gitignore
- src/QueryReflection/MysqliQueryReflector.php
- tests/rules/config/.phpunit-phpstan-dba-pdo-mysql.cache
- tests/rules/data/query-plan-analyzer.php
closes https://github.com/staabm/phpstan-dba/issues/442
> fix fatal error on mysql error 1103 / incorrect table

- src/Rules/QueryPlanAnalyzerRule.php
- src/Rules/SyntaxErrorInQueryFunctionRule.php
- src/Rules/SyntaxErrorInQueryMethodRule.php
should fix https://github.com/staabm/phpstan-dba/issues/452
partly reverts https://github.com/staabm/phpstan-dba/commit/6a172b05697e268ee7649070e9e7bc65b544e2da
> fixed regression

- src/QueryReflection/QueryReflection.php
- tests/rules/data/syntax-error-in-prepared-statement.php
- tests/rules/data/syntax-error-in-query-function.php
- tests/rules/data/syntax-error-in-query-method.php
fixes https://github.com/staabm/phpstan-dba/issues/442#issuecomment-1299918699
> prevent `Query error: Incorrect table name '' (1103).`

- src/Extensions/DeployerRunMysqlQueryDynamicReturnTypeExtension.php
- src/Extensions/DoctrineConnectionExecuteQueryDynamicReturnTypeExtension.php
- src/Extensions/DoctrineConnectionFetchDynamicReturnTypeExtension.php
- src/Extensions/DoctrineConnectionPrepareDynamicReturnTypeExtension.php
- src/Extensions/DoctrineConnectionQueryDynamicReturnTypeExtension.php
- src/Extensions/DoctrineResultDynamicReturnTypeExtension.php
- src/Extensions/DoctrineStatementExecuteDynamicReturnTypeExtension.php
- src/Extensions/PdoStatementColumnCountDynamicReturnTypeExtension.php
- src/Extensions/PdoStatementFetchObjectDynamicReturnTypeExtension.php
- tests/default/config/.phpunit-phpstan-dba-mysqli.cache
- tests/default/config/.phpunit-phpstan-dba-pdo-mysql.cache
- tests/rules/config/.phpunit-phpstan-dba-mysqli.cache
- tests/rules/config/.phpunit-phpstan-dba-pdo-mysql.cache
supported since phpstan 1.5.0 
https://github.com/phpstan/phpstan-src/commit/a897d3a4a0bc1cc8a385eab34da399a75969a538
> simplify return type extensions

- src/DibiReflection/DibiReflection.php
- src/Extensions/DibiConnectionFetchDynamicReturnTypeExtension.php
- src/Rules/SyntaxErrorInDibiPreparedStatementMethodRule.php
- tests/default/config/.phpunit-phpstan-dba-mysqli.cache
- tests/rules/SyntaxErrorInDibiPreparedStatementMethodRuleTest.php
- tests/rules/config/.phpunit-phpstan-dba-mysqli.cache
I could push into your PR so I create a new one.
is this what you mean by fixing the extension? The tests passed when i tried to run them locally afaik. Hopefully they will pass CI here as well
> Fix inference in dynamic return extension

- .github/workflows/tests-postgres.yml
- .github/workflows/tests.yml
the teamcity format is ugly and hard to read in the github action logfiles ... grr
> fix github action phpunit annotations

- .github/workflows/phpstan.yml
- config/Mysqli.stub
refs https://github.com/staabm/phpstan-dba/issues/466
overlaps with https://github.com/phpstan/phpstan-src/blob/253316f50dcafb60a6e1e603d16de9078d27ad44/stubs/mysqli.stub#L3
> remove duplicate mysqli_stmt stub definitions

- src/QueryReflection/PdoMysqlQueryReflector.php
- src/QueryReflection/PdoPgSqlQueryReflector.php
required for https://github.com/staabm/phpstan-dba/pull/483 to make sure we will hard-fail before running a destructive query in the real database
> Throw exception in case we are not able to start a transaction

- .phpstan-dba-mysqli.cache
- .phpstan-dba-pdo-mysql.cache
- README.md
- docs/configuration.md
- src/Analyzer/QueryPlanAnalyzerMysql.php
- src/DbSchema/SchemaHasherMysql.php
- src/QueryReflection/MysqliQueryReflector.php
- src/QueryReflection/QueryReflection.php
- src/QueryReflection/RuntimeConfiguration.php
- tests/default/config/.phpunit-phpstan-dba-mysqli.cache
- tests/default/config/.phpunit-phpstan-dba-pdo-mysql.cache
- tests/defaultFetchAssoc/config/.phpunit-phpstan-dba-mysqli.cache
- tests/defaultFetchAssoc/config/.phpunit-phpstan-dba-pdo-mysql.cache
- tests/defaultFetchNumeric/config/.phpunit-phpstan-dba-mysqli.cache
- tests/defaultFetchNumeric/config/.phpunit-phpstan-dba-pdo-mysql.cache
- tests/rules/SyntaxErrorInDibiPreparedStatementMethodRuleTest.php
- tests/rules/SyntaxErrorInPreparedStatementMethodRuleTest.php
- tests/rules/SyntaxErrorInQueryMethodRuleTest.php
- tests/rules/config/.phpunit-phpstan-dba-mysqli.cache
- tests/rules/config/.phpunit-phpstan-dba-pdo-mysql.cache
- tests/stringify/config/.phpunit-phpstan-dba-mysqli.cache
- tests/stringify/config/.phpunit-phpstan-dba-pdo-mysql.cache
followup to https://github.com/staabm/phpstan-dba/pull/483
closes https://github.com/staabm/phpstan-dba/issues/496
> transform write query into read query

- .phpstan-dba-mysqli.cache
- .phpstan-dba-pdo-mysql.cache
- tests/default/DbaInferenceTest.php
- tests/default/config/.phpunit-phpstan-dba-pdo-mysql.cache
seems this one passes now..
closes https://github.com/staabm/phpstan-dba/issues/279
> Enable query-alias-test for pdo-mysql

- .phpstan-dba-mysqli.cache
- .phpstan-dba-pdo-mysql.cache
- bootstrap.php
- composer.json
- phpstan-baseline.neon
- src/QueryReflection/QueryReflection.php
- tests/default/data/pdo-mysql.php
closes https://github.com/staabm/phpstan-dba/issues/541
> Fix query building with constant assignments

- .phpstan-dba-mysqli.cache
- src/QueryReflection/QueryReflection.php
- tests/rules/SyntaxErrorInQueryMethodRuleTest.php
- tests/rules/UnresolvableQueryMethodRuleTest.php
- tests/rules/config/.phpunit-phpstan-dba-mysqli.cache
- tests/rules/config/.phpunit-phpstan-dba-pdo-mysql.cache
- tests/rules/data/bug-547.php
closes https://github.com/staabm/phpstan-dba/issues/547
> Fix query simulation leading to query error

- tests/rules/SyntaxErrorInQueryMethodRuleTest.php
- tests/rules/UnresolvableQueryMethodRuleTest.php
- tests/rules/data/bug-548.php
closes https://github.com/staabm/phpstan-dba/issues/548
> Fix another query simulation leading to query error

- tests/rules/data/syntax-error-in-prepared-statement.php
- tests/rules/data/syntax-error-in-query-function.php
- tests/rules/data/syntax-error-in-query-method.php
closes https://github.com/staabm/phpstan-dba/issues/458
> error on from table-name create from function-call 

- src/QueryReflection/QueryReflection.php
closes https://github.com/staabm/phpstan-dba/issues/559
> SQL AST inference is only supported for mysql backends for now

- config/dba.neon
workaround for https://github.com/staabm/phpstan-dba/issues/466 until we find a better solution
> Disable duplicate stub validation for now

- src/DbSchema/LazySchemaHasher.php
- src/DbSchema/SchemaHasher.php
- src/DbSchema/SchemaHasherMysql.php
- src/QueryReflection/PdoMysqlQueryReflector.php
- src/QueryReflection/ReplayAndRecordingQueryReflector.php
There is `LazyQueryReflector `, but the `SchemaHasherMysql` still always needs a connection. With this one could defer this too.
> add LazySchemaHasher

- .github/dependabot.yml
There are outdated actions.
[_source_](https://github.com/szepeviktor/byte-level-care/blob/master/.github/dependabot.yml)
> Make Dependabot update actions

- .github/workflows/tests.yml
Just using Composer the right way.
> Fix Composer usage in Unit Tests MySQL workflow

- composer.json
followup to https://github.com/staabm/phpstan-dba/pull/652
refs https://github.com/staabm/phpstan-dba/issues/653
> Fix composer scripts for doctrine/dbal 3.x

- composer.json
closes https://github.com/staabm/phpstan-dba/issues/689
> Keep sqlftw/sqlftw a optional dependency

- config/dba.neon
- src/Extensions/MysqliQueryDynamicReturnTypeExtension.php
- src/MysqliReflection/MysqliResultObjectType.php
cleanup leftover of https://github.com/staabm/phpstan-dba/pull/698
> Remove mysqli_result from skipCheckGenericClasses

- src/QueryReflection/ReflectionCache.php
regression from https://github.com/staabm/phpstan-dba/commit/7653a6ec74f470a912a9bde05db09a88b80bbdaa
> Fix replay

- src/DoctrineReflection/DoctrineReflection.php
- tests/default/data/doctrine-dbal.php
closes https://github.com/staabm/phpstan-dba/issues/719
> doctrine-dbal might return `list`

- src/Ast/ExpressionFinder.php
- src/Ast/PreviousConnectingVisitor.php
see https://github.com/nikic/PHP-Parser/issues/1055#issuecomment-2565291102
refs https://github.com/staabm/phpstan-dba/issues/667
> PreviousConnectingVisitor: Utilize WeakReference to assist garbage collector

- tests/default/data/typemix-mysql.php
- tests/default/data/typemix-pgsql.php
> Remove redundant test and constants

- src/Rules/DoctrineKeyValueStyleRule.php
- src/Rules/QueryPlanAnalyzerRule.php
- src/Rules/SyntaxErrorInDibiPreparedStatementMethodRule.php
- src/Rules/SyntaxErrorInPreparedStatementMethodRule.php
- src/Rules/SyntaxErrorInQueryMethodRule.php
fixes regression from https://github.com/staabm/phpstan-dba/pull/755
refs https://github.com/staabm/phpstan-dba/issues/756#issuecomment-2853930507
> Added missing `ReflectionProvider->hasClass()` checks

- src/QueryReflection/QuerySimulation.php
- tests/default/QuerySimulationTest.php
refs https://github.com/yakamara/ydeploy/pull/101#issuecomment-3090150990
> Prevent endless loop in `QuerySimulation`
